// AUTO-GENERATED from Nespresso_Original_Capsules.csv - do not edit by hand

export const generatedProducts = [
  {
    slug: "arpeggio",
    name: "کپسول قهوه نسپرسو Arpeggio",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 9,
    badge: undefined,
    desc: "Arpeggio یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۹ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کاکائو، پرشور، خامه‌ای است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۹ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7928.40.jpg",
  },
  {
    slug: "arpeggio-decaffeinato",
    name: "کپسول قهوه نسپرسو Arpeggio Decaffeinato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 39.9,
    rating: 4.6,
    reviews: 79.9,
    intensity: 9,
    badge: "بدون کافئین",
    desc: "Arpeggio Decaffeinato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۹ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شدید برشته، خامه‌ای است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۹ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین","بدون کافئین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7943.40.jpg",
  },
  {
    slug: "arpeggio-extra",
    name: "کپسول قهوه نسپرسو Arpeggio Extra",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 41.9,
    rating: 4.8,
    reviews: 81.9,
    intensity: 9,
    badge: undefined,
    desc: "Arpeggio Extra یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۹ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کاکائو، شدید برشته است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۹ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7967.40.jpg",
  },
  {
    slug: "athens-freddo-intenso",
    name: "کپسول قهوه نسپرسو Athens Freddo Intenso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Athens Freddo Intenso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان برشته است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و نوشیدنی سرد طراحی شده است. روی یخ فراوان امتحانش کنید تا خنکی و تعادل طعمش را همزمان تجربه کنید.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، نوشیدنی سرد","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7944.40.jpg",
  },
  {
    slug: "barista-coffee-selection-80-capsules",
    name: "کپسول قهوه نسپرسو Barista Coffee Selection - 80 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 3370,
    rating: 4.3,
    reviews: 50,
    intensity: 0,
    badge: "ست پک",
    desc: "Barista Coffee Selection - 80 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۸۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۸۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_136226.jpg",
  },
  {
    slug: "buenos-aires-lungo",
    name: "کپسول قهوه نسپرسو Buenos Aires Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 4,
    badge: undefined,
    desc: "Buenos Aires Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۴ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان غلات، شیرین است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۴ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7946.40.jpg",
  },
  {
    slug: "cape-town-lungo",
    name: "کپسول قهوه نسپرسو Cape Town Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 10,
    badge: undefined,
    desc: "Cape Town Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۰ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان چوبی، برشته است و شخصیت کلی‌اش عمیق و پرشور ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۱۰ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7948.40.jpg",
  },
  {
    slug: "capriccio",
    name: "کپسول قهوه نسپرسو Capriccio",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 5,
    badge: undefined,
    desc: "Capriccio یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۵ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان پرشکوه، متمایز است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۵ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7961.40.jpg",
  },
  {
    slug: "caramello",
    name: "کپسول قهوه نسپرسو Caramello",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Caramello یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کاراملی، بیسکویتی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو و نوشیدنی شیردار طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو، نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7964.40.jpg",
  },
  {
    slug: "chiaro",
    name: "کپسول قهوه نسپرسو Chiaro",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Chiaro یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شیرین، نرم است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری نوشیدنی شیردار طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["پیشنهاد دم‌آوری: نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7892.40.jpg",
  },
  {
    slug: "cinnamon-and-candied-tamarind",
    name: "کپسول قهوه نسپرسو Cinnamon & Candied Tamarind",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Cinnamon & Candied Tamarind یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان دارچینی، تاماریند است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7903.40.jpg",
  },
  {
    slug: "cioccolatino",
    name: "کپسول قهوه نسپرسو Cioccolatino",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Cioccolatino یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شکلاتی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو و نوشیدنی شیردار طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو، نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7968.40.jpg",
  },
  {
    slug: "colombia",
    name: "کپسول قهوه نسپرسو Colombia",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 6,
    badge: undefined,
    desc: "Colombia یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۶ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان زنده، میوه‌ای است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۶ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7929.40.jpg",
  },
  {
    slug: "corto",
    name: "کپسول قهوه نسپرسو Corto",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Corto یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان پرشور است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری نوشیدنی شیردار طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["پیشنهاد دم‌آوری: نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7871.40.jpg",
  },
  {
    slug: "cosi",
    name: "کپسول قهوه نسپرسو Cosi",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 4,
    badge: undefined,
    desc: "Cosi یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۴ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان لایت، لطیف برشته است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۴ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7969.40.jpg",
  },
  {
    slug: "ethiopia",
    name: "کپسول قهوه نسپرسو Ethiopia",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 4,
    badge: undefined,
    desc: "Ethiopia یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۴ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان گلی، زنده است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۴ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7886.40.jpg",
  },
  {
    slug: "fall-coffee-selection-100-capsules",
    name: "کپسول قهوه نسپرسو Fall Coffee Selection - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 4460,
    rating: 4.4,
    reviews: 180,
    intensity: 0,
    badge: "ست پک",
    desc: "Fall Coffee Selection - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_161408.jpg",
  },
  {
    slug: "fall-coffee-selection-100-capsules-old",
    name: "کپسول قهوه نسپرسو Fall Coffee Selection - 100 Capsules - OLD",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 2420,
    rating: 3.9,
    reviews: 60,
    intensity: 0,
    badge: "ست پک",
    desc: "Fall Coffee Selection - 100 Capsules - OLD یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_145524.jpg",
  },
  {
    slug: "festive-collection-espresso",
    name: "کپسول قهوه نسپرسو Festive Collection Espresso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 7,
    badge: undefined,
    desc: "Festive Collection Espresso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۷ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان غلات، چوبی، میوه‌ای است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۷ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7919.40.jpg",
  },
  {
    slug: "filter-style-intense",
    name: "کپسول قهوه نسپرسو Filter Style Intense",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 42.9,
    rating: 4.9,
    reviews: 82.9,
    intensity: 0,
    badge: undefined,
    desc: "Filter Style Intense یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان دودی، برشته است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7780.40.jpg",
  },
  {
    slug: "filter-style-mild",
    name: "کپسول قهوه نسپرسو Filter Style Mild",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 42.9,
    rating: 4.9,
    reviews: 82.9,
    intensity: 0,
    badge: undefined,
    desc: "Filter Style Mild یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان گلی، مالتی غلات است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7783.40.jpg",
  },
  {
    slug: "freddo-delicato",
    name: "کپسول قهوه نسپرسو Freddo Delicato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Freddo Delicato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان میوه‌ای، شیرین است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و نوشیدنی سرد طراحی شده است. روی یخ فراوان امتحانش کنید تا خنکی و تعادل طعمش را همزمان تجربه کنید.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، نوشیدنی سرد","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7870.40.jpg",
  },
  {
    slug: "freddo-intenso",
    name: "کپسول قهوه نسپرسو Freddo Intenso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Freddo Intenso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان برشته است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و نوشیدنی سرد طراحی شده است. روی یخ فراوان امتحانش کنید تا خنکی و تعادل طعمش را همزمان تجربه کنید.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، نوشیدنی سرد","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7883.40.jpg",
  },
  {
    slug: "india",
    name: "کپسول قهوه نسپرسو India",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 11,
    badge: "پرشور",
    desc: "India یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۱ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان ادویه‌ای، پرشور، چوبی است و شخصیت کلی‌اش عمیق و پرشور ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۱۱ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7977.40.jpg",
  },
  {
    slug: "indonesia",
    name: "کپسول قهوه نسپرسو Indonesia",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 8,
    badge: undefined,
    desc: "Indonesia یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان چوبی، پرشکوه است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7975.40.jpg",
  },
  {
    slug: "ispirazione-italiana-coffee-selection-100-capsules",
    name: "کپسول قهوه نسپرسو Ispirazione Italiana Coffee Selection - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 3920,
    rating: 4.3,
    reviews: 120,
    intensity: 0,
    badge: "ست پک",
    desc: "Ispirazione Italiana Coffee Selection - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_164764.jpg",
  },
  {
    slug: "ispirazione-napoli",
    name: "کپسول قهوه نسپرسو Ispirazione Napoli",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 13,
    badge: "پرشور",
    desc: "Ispirazione Napoli یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۳ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان فوق‌العاده پرشور، خامه‌ای است و شخصیت کلی‌اش بسیار تند و سنگین ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و ریستروتتو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۱۳ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، ریستروتتو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7984.40.jpg",
  },
  {
    slug: "ispirazione-roma",
    name: "کپسول قهوه نسپرسو Ispirazione Roma",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 8,
    badge: undefined,
    desc: "Ispirazione Roma یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، پرشور است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و ریستروتتو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، ریستروتتو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7985.40.jpg",
  },
  {
    slug: "ispirazione-venezia",
    name: "کپسول قهوه نسپرسو Ispirazione Venezia",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 8,
    badge: undefined,
    desc: "Ispirazione Venezia یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، پرحجم است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7986.40.jpg",
  },
  {
    slug: "istanbul-espresso",
    name: "کپسول قهوه نسپرسو Istanbul Espresso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 42.9,
    rating: 4.9,
    reviews: 82.9,
    intensity: 8,
    badge: undefined,
    desc: "Istanbul Espresso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان میوه‌ای، بادامی است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7877.40.jpg",
  },
  {
    slug: "kazaar",
    name: "کپسول قهوه نسپرسو Kazaar",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 12,
    badge: "پرشور",
    desc: "Kazaar یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۲ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شربتی، فوق‌العاده پرشور است و شخصیت کلی‌اش بسیار تند و سنگین ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۱۲ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7972.40.jpg",
  },
  {
    slug: "light-roast-coffee-selection-50-capsules",
    name: "کپسول قهوه نسپرسو LIGHT ROAST COFFEE SELECTION - 50 CAPSULES",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 1020,
    rating: 4.7,
    reviews: 100,
    intensity: 0,
    badge: "ست پک",
    desc: "LIGHT ROAST COFFEE SELECTION - 50 CAPSULES یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۵۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۵۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_135411.jpg",
  },
  {
    slug: "livanto",
    name: "کپسول قهوه نسپرسو Livanto",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 7,
    badge: undefined,
    desc: "Livanto یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۷ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کاراملی، متعادل است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۷ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7979.40.jpg",
  },
  {
    slug: "lungo-coffee-selection-100-capsules",
    name: "کپسول قهوه نسپرسو Lungo Coffee Selection - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 3729,
    rating: 3.9,
    reviews: 89,
    intensity: 0,
    badge: "ست پک",
    desc: "Lungo Coffee Selection - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_157966.jpg",
  },
  {
    slug: "milano-intenso",
    name: "کپسول قهوه نسپرسو MILANO INTENSO",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 22.5,
    rating: 3.9,
    reviews: 62.5,
    intensity: 8,
    badge: undefined,
    desc: "MILANO INTENSO یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کاکائو، غلات است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7791.40.jpg",
  },
  {
    slug: "maple-pecan-original",
    name: "کپسول قهوه نسپرسو Maple Pecan - Original",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Maple Pecan - Original یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان افره‌ایم، pecan آجیل است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7917.40.jpg",
  },
  {
    slug: "nespresso-t-rkiye-best-sellers-100-capsules",
    name: "کپسول قهوه نسپرسو Nespresso Türkiye Best Sellers - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 4250,
    rating: 4.3,
    reviews: 130,
    intensity: 0,
    badge: undefined,
    desc: "Nespresso Türkiye Best Sellers - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_135410.jpg",
  },
  {
    slug: "nespresso-welcoming-selection-200-capsules",
    name: "کپسول قهوه نسپرسو Nespresso Welcoming Selection - 200 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 8510,
    rating: 4.6,
    reviews: 70,
    intensity: 0,
    badge: "ست پک",
    desc: "Nespresso Welcoming Selection - 200 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۲۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۲۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_135413.jpg",
  },
  {
    slug: "nicaragua",
    name: "کپسول قهوه نسپرسو Nicaragua",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 5,
    badge: undefined,
    desc: "Nicaragua یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۵ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شیرین غلات، متعادل است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۵ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7973.40.jpg",
  },
  {
    slug: "nocciola",
    name: "کپسول قهوه نسپرسو Nocciola",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Nocciola یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان آجیلی، پرشکوه است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو و نوشیدنی شیردار طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو، نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7937.40.jpg",
  },
  {
    slug: "original-summer-coffee-selection-100-capsules",
    name: "کپسول قهوه نسپرسو Original Summer Coffee Selection - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 4550,
    rating: 4.6,
    reviews: 110,
    intensity: 0,
    badge: "ست پک",
    desc: "Original Summer Coffee Selection - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_165785.jpg",
  },
  {
    slug: "paris-espresso",
    name: "کپسول قهوه نسپرسو Paris Espresso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 42.9,
    rating: 4.9,
    reviews: 82.9,
    intensity: 6,
    badge: undefined,
    desc: "Paris Espresso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۶ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان بیسکویتی، مرکباتی، غلات است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۶ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7965.40.jpg",
  },
  {
    slug: "peanut-and-roasted-sesame-flavour-original-coffee",
    name: "کپسول قهوه نسپرسو Peanut and Roasted Sesame Flavour Original Coffee",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Peanut and Roasted Sesame Flavour Original Coffee یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان غلات، کنجد، بادام‌زمینی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7850.04.jpg",
  },
  {
    slug: "pistachio-vanilla-flavour-over-ice-original",
    name: "کپسول قهوه نسپرسو Pistachio Vanilla Flavour Over Ice - Original",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Pistachio Vanilla Flavour Over Ice - Original یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان ته‌مایه وانیلی، بادامی، کاراملی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و نوشیدنی سرد طراحی شده است. روی یخ فراوان امتحانش کنید تا خنکی و تعادل طعمش را همزمان تجربه کنید.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، نوشیدنی سرد","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7906.40.jpg",
  },
  {
    slug: "premium-coffee-selection-50-capsules",
    name: "کپسول قهوه نسپرسو Premium Coffee Selection - 50 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 2185,
    rating: 4.6,
    reviews: 145,
    intensity: 0,
    badge: "ست پک",
    desc: "Premium Coffee Selection - 50 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۵۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۵۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_155475.jpg",
  },
  {
    slug: "pumpkin-spice-cake-original",
    name: "کپسول قهوه نسپرسو Pumpkin Spice Cake - Original",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Pumpkin Spice Cake - Original یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان کدوحلوایی، ادویه‌ای، دارچینی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7835.40.jpg",
  },
  {
    slug: "rio-de-janeiro-espresso",
    name: "کپسول قهوه نسپرسو Rio De Janeiro Espresso",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 42.9,
    rating: 4.9,
    reviews: 82.9,
    intensity: 9,
    badge: undefined,
    desc: "Rio De Janeiro Espresso یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۹ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان ادویه‌ای، گلی است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۹ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7966.40.jpg",
  },
  {
    slug: "ristretto",
    name: "کپسول قهوه نسپرسو Ristretto",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 10,
    badge: undefined,
    desc: "Ristretto یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۰ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شدید برشته، ته‌مایه میوه‌ای است و شخصیت کلی‌اش عمیق و پرشور ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و ریستروتتو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۱۰ از ۱۳","پیشنهاد دم‌آوری: اسپرسو، ریستروتتو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7987.40.jpg",
  },
  {
    slug: "ristretto-decaffeinato",
    name: "کپسول قهوه نسپرسو Ristretto Decaffeinato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 39.9,
    rating: 4.6,
    reviews: 79.9,
    intensity: 10,
    badge: "بدون کافئین",
    desc: "Ristretto Decaffeinato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۱۰ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان شدید برشته، غلات، متضاد است و شخصیت کلی‌اش عمیق و پرشور ارزیابی می‌شود. این کپسول برای دم‌آوری ریستروتتو و اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۱۰ از ۱۳","پیشنهاد دم‌آوری: ریستروتتو، اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین","بدون کافئین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7980.40.jpg",
  },
  {
    slug: "scuro",
    name: "کپسول قهوه نسپرسو Scuro",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Scuro یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، پرشور است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری نوشیدنی شیردار طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["پیشنهاد دم‌آوری: نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7891.40.jpg",
  },
  {
    slug: "shanghai-lungo",
    name: "کپسول قهوه نسپرسو Shanghai Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 5,
    badge: undefined,
    desc: "Shanghai Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۵ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان مرکباتی، توت‌فرنگی، میوه‌ای است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۵ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7947.40.jpg",
  },
  {
    slug: "stockholm-lungo",
    name: "کپسول قهوه نسپرسو Stockholm Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 8,
    badge: undefined,
    desc: "Stockholm Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۸ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان برشته، قدرتمند، پر,  است و شخصیت کلی‌اش پرقدرت ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۸ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7926.40.jpg",
  },
  {
    slug: "sweet-almond-and-hibiscus",
    name: "کپسول قهوه نسپرسو Sweet Almond & Hibiscus",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Sweet Almond & Hibiscus یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان بادامی، Hibiscus است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7907.40.jpg",
  },
  {
    slug: "tokyo-lungo",
    name: "کپسول قهوه نسپرسو Tokyo Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 6,
    badge: undefined,
    desc: "Tokyo Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۶ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان گل‌دار، برشته است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۶ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7936.40.jpg",
  },
  {
    slug: "vanilla-eclair",
    name: "کپسول قهوه نسپرسو VANILLA ÉCLAIR",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 22,
    rating: 3.9,
    reviews: 62,
    intensity: 0,
    badge: undefined,
    desc: "VANILLA ÉCLAIR یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان وانیلی، متعادل، مالتی غلات است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو و نوشیدنی شیردار طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["پیشنهاد دم‌آوری: اسپرسو، نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7753.40.jpg",
  },
  {
    slug: "vaniglia",
    name: "کپسول قهوه نسپرسو Vaniglia",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 0,
    badge: undefined,
    desc: "Vaniglia یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان وانیلی، بیسکویتی است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو و نوشیدنی شیردار طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو، نوشیدنی شیردار","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7933.40.jpg",
  },
  {
    slug: "vaniglia-decaffeinato",
    name: "کپسول قهوه نسپرسو Vaniglia Decaffeinato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 47.9,
    rating: 4.3,
    reviews: 87.9,
    intensity: 0,
    badge: "بدون کافئین",
    desc: "Vaniglia Decaffeinato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان وانیلی، آجیلی، میوه‌ای است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین","بدون کافئین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7988.40.jpg",
  },
  {
    slug: "vienna-lungo",
    name: "کپسول قهوه نسپرسو Vienna Lungo",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 45.9,
    rating: 4.1,
    reviews: 85.9,
    intensity: 6,
    badge: undefined,
    desc: "Vienna Lungo یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۶ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، نرم است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۶ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7959.40.jpg",
  },
  {
    slug: "vienna-lungo-decaffeinato",
    name: "کپسول قهوه نسپرسو Vienna Lungo Decaffeinato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 46.9,
    rating: 4.2,
    reviews: 86.9,
    intensity: 7,
    badge: "بدون کافئین",
    desc: "Vienna Lungo Decaffeinato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۷ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان غلات، شیرین است و شخصیت کلی‌اش متعادل و خوش‌توازن ارزیابی می‌شود. این کپسول برای دم‌آوری لونگو طراحی شده است. حجم بلند لونگو اجازه می‌دهد لایه‌های طعمی‌اش آرام‌آرام باز شوند.",
    features: ["شدت طعم ۷ از ۱۳","پیشنهاد دم‌آوری: لونگو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین","بدون کافئین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7051.40.jpg",
  },
  {
    slug: "volluto",
    name: "کپسول قهوه نسپرسو Volluto",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 38.9,
    rating: 4.5,
    reviews: 78.9,
    intensity: 4,
    badge: undefined,
    desc: "Volluto یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۴ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، میوه‌ای، غلات است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۴ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7983.40.jpg",
  },
  {
    slug: "volluto-decaffeinato",
    name: "کپسول قهوه نسپرسو Volluto Decaffeinato",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 39.9,
    rating: 4.6,
    reviews: 79.9,
    intensity: 4,
    badge: "بدون کافئین",
    desc: "Volluto Decaffeinato یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ شدت طعم آن ۴ از ۱۳ ثبت شده است و در بسته ۱۰ عددی ارائه می‌شود. نت‌های غالب فنجان متعادل، غلات، میوه‌ای است و شخصیت کلی‌اش ملایم و لطیف ارزیابی می‌شود. این کپسول برای دم‌آوری اسپرسو طراحی شده است. بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["شدت طعم ۴ از ۱۳","پیشنهاد دم‌آوری: اسپرسو","بسته ۱۰ عددی","سازگار با دستگاه‌های اورجینال لاین","بدون کافئین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_7932.40.jpg",
  },
  {
    slug: "world-explorations-coffee-selection-100-capsules",
    name: "کپسول قهوه نسپرسو World Explorations Coffee Selection - 100 Capsules",
    brand: "Nespresso",
    category: "capsule-original",
    priceTry: 4470,
    rating: 4.3,
    reviews: 190,
    intensity: 0,
    badge: "ست پک",
    desc: "World Explorations Coffee Selection - 100 Capsules یکی از اعضای خانواده کپسول‌های نسپرسو اورجینال لاین است؛ و در بسته ۱۰۰ عددی ارائه می‌شود.   بهترین حالتش در حجم کوتاه است؛ یک ریستروتتوی ۲۵ میلی‌لیتری یا اسپرسوی ۴۰ میلی‌لیتری.",
    features: ["بسته ۱۰۰ عددی","سازگار با دستگاه‌های اورجینال لاین"],
    art: { type: "capsule", from: "#2b1d13", to: "#8a6a4f" },
    img: "/images/products/nespresso/main_135414.jpg",
  },
];
